"""
Helper script to visualize dense point clouds from the output of dmap_zncc.py

This script loads the depth values (TA) and corresponding pixel coordinates (PA) from
the output .mat files generated by the driver scripts, and then computes the 3D point
cloud using the camera parameters (P).

The resulting point cloud can be visualized using various libraries such as matplotlib,
pptk, or open3d.
"""

import numpy as np
import scipy.io as spio
import matplotlib.pyplot as plt
import sys, os.path as path
sys.path.append(path.dirname(path.dirname(path.abspath(__file__))))
import modules.func as func


# Image dataset
data_path = 'data'
dataset = 'dinoRing'

fpath = path.join(data_path, dataset + '_dmaps.mat')
mfile = spio.loadmat(fpath)
FA = mfile['FA']
PA = mfile['PA']
TA = mfile['TA']

fpath = path.join(data_path, dataset, dataset + '_P.mat')
mfile = spio.loadmat(fpath)
P = mfile['P']

FA = np.squeeze(FA)
TA = np.squeeze(TA)

# Select points with high fitness
idx = np.where(FA < -4.5)[0]
FA = FA[idx]
PA = PA[idx]
TA = TA[idx]

ncam = len(P)
npts = PA.shape[0]
npts = 100000                               # Limit no of points to plot

# Compute 3D point cloud
XA = np.zeros((3,npts))
for i in range(npts):
    imx0, x, y = PA[i]
    pt = np.array(([x],[y], [1]))
    rpos, rdir = func.camera_ray(P[imx0], pt)
    X = rpos + TA[i] * rdir
    XA[:,i,None] = X

# 3D plot using matplotlib
fig = plt.figure()
ax = fig.gca(projection='3d')
# plt.axis('off')
plt.tight_layout()
ax.plot(XA[0], XA[1], XA[2], 'r.', markersize=1)
print('Plotting {} 3D points'.format(npts))

# 3D plot using pptk
import pptk
XA2 = XA.T
v = pptk.viewer(XA2)

# 3D plot using open3d
import open3d as o3d
pcd = o3d.geometry.PointCloud()
XA2 = XA.T
pcd.points = o3d.utility.Vector3dVector(XA2)
o3d.visualization.draw_geometries([pcd])
