'''
Merge two depth maps using pixel-edge distance and apply adaptive median smoothing.

This helper script processes depth maps generated by dmap_zncc.py and dmap_daisy.py
to produce filtered depth maps compatible with the MVE pipeline. The script can
optionally perform foreground masking, low-confidence filtering using fitness maps,
depth bounds filtering, and cross-view consistency checks before exporting the final
depth maps in MVE format.

Pipeline:
1. Load two depth maps (D1, D2) and their fitness maps (F1, F2).
2. Compute pixel-edge distance maps (EM) from input images using Canny edge detection
   followed by a distance transform.
3. Merge depth maps based on EM thresholding (use D1 near edges, D2 elsewhere).
4. Apply adaptive median smoothing on the merged depth map based on EM.
5. (Optional) Apply foreground segmentation using a binary mask
6. (Optional) Remove low confidence depth values based on fitness maps F1 and F2
7. (Optional) Remove depth values outside bounds [B_low, B_high]
8. (Optional) Apply cross-view consistency check to further filter the depthmaps
9. Write the final depth maps to the MVE scene directory in .mvei format.

Notes:
- Input depth maps are expected as `.mat` files containing variables: FA, PA, TA.
- Images and foreground masks must follow the expected directory structure.
- The script can be configured to run in parallel for adaptive median filtering and
  cross-view consistency checks, which can be computationally intensive.
'''

import numpy as np
import scipy.io as spio
import scipy.ndimage as ndimage
import cv2
from tqdm import tqdm
import sys, os.path as path
sys.path.append(path.dirname(path.dirname(path.abspath(__file__))))
import modules.func as func


# Single core or parallel execution
is_parallel = True

# Image dataset and resolution (width, height)
data_path = 'data'
dataset = 'dinoRing'
res = (640, 480)

# Bounds for clipping depth values (set to -inf and inf for no bounds checking)
B_low = 0.6             # DinoRing
B_high = 0.7
# B_low = -np.inf         # No bounds checking
# B_high = np.inf

# MVE scene parameters
is_write_scene = True
scene_idx = 0
depth_level = 0
scene_path = 'data\\MVE-20190610\\scene-' + str(dataset) + '-' + str(scene_idx)

# Indices of depthmaps to merge (corresponding to dmap_zncc.py and dmap_daisy.py)
dmap_idx_1 = 1
dmap_idx_2 = 2

# Multiplier for adaptive median
adap_median_multiplier = 1.0

# Fitness thresholds for filtering depth values (set to inf for no fitness checking)
thresh_F1 = -4.6        # ZNCC
thresh_F2 = 1.3         # DAISY
# thresh_F1 = np.inf      # No fitness checking
# thresh_F2 = np.inf

# Parameters for pixel-edge distance (PED) calculation and merging
canny_low = 80              # Canny low threshold
canny_high = 100            # Canny high threshold
ped_offset = 3              # Offset added to PED to avoid zero distance (and thus zero median size) at edges
thresh_merge = 10           # PED threshold for merging depthmaps (use D1 if PED < thresh_merge, else D2)


# Progress bar update callback for parallel processing
def pbar_update(p):
    pbar.update()


if __name__ == '__main__':
    # Print info
    print('')
    print('********************************************')
    print('Merge depthmaps based on pixel-edge distance')
    print('********************************************')
    print('')
    print('Dataset                  : {}'.format(dataset))
    print('Bounds                   : [{}, {}]'.format(B_low, B_high))
    print('Scene [depth-level]      : {} [{}]'.format(scene_idx, depth_level))
    print('Dense files              : {}, {}'.format(dmap_idx_1, dmap_idx_2))
    print('Fitness thresholds       : {}, {}'.format(thresh_F1, thresh_F2))
    print('Adap median multiplier   : {}'.format(adap_median_multiplier))
    print('PED Canny thresholds     : {}, {}'.format(canny_low, canny_high))
    print('PED merge threshold      : {}'.format(thresh_merge))
    print('PED offset               : {}'.format(ped_offset))
    print('')

    # Load images
    im_dir = path.join(data_path, dataset, 'images')
    I = func.load_images_from_folder(im_dir, 0)

    # Load data 1 (assumed to be dmap_zncc.py output)
    fpath = path.join(data_path, dataset + '_dmaps_' + str(dmap_idx_1) + '.mat')
    mfile = spio.loadmat(fpath)
    FA = mfile['FA']
    PA = mfile['PA']
    TA = mfile['TA']
    FA = np.squeeze(FA)
    TA = np.squeeze(TA)
    n_pts = PA.shape[0]
    n_cam = np.max(PA[:,0]) + 1          # PA need not contain all cameras

    # Depth & Fitness maps 1
    D1 = np.zeros((n_cam, res[1], res[0]))
    F1 = np.zeros((n_cam, res[1], res[0]))
    print('Loading depth and fitness values from \'{}.mat\'...'.format(dmap_idx_1), flush=True)
    for i in tqdm(range(n_pts)):
        imi, xi, yi = PA[i]
        D1[imi, yi, xi] = TA[i]
        F1[imi, yi, xi] = FA[i]

    # Load data 2 (assumed to be dmap_daisy.py output)
    fpath = path.join(data_path, dataset + '_dmaps_' + str(dmap_idx_2) + '.mat')
    mfile = spio.loadmat(fpath)
    FA = mfile['FA']
    PA = mfile['PA']
    TA = mfile['TA']
    FA = np.squeeze(FA)
    TA = np.squeeze(TA)

    n_pts = PA.shape[0]

    # Depth & Fitness maps 2
    D2 = np.zeros((n_cam, res[1], res[0]))
    F2 = np.zeros((n_cam, res[1], res[0]))
    print('Loading depth and fitness values from \'{}.mat\'...'.format(dmap_idx_2), flush=True)
    for i in tqdm(range(n_pts)):
        imi, xi, yi = PA[i]
        D2[imi, yi, xi] = TA[i]
        F2[imi, yi, xi] = FA[i]

    # Load foreground masks
    mask_dir = path.join(data_path, dataset, 'foreground_mask')
    M = func.load_images_from_folder(mask_dir, 0)               # 0/255 binary
    if (np.unique(M)[0] == 0) and (np.unique(M)[1] == 255):
        M = M.astype(np.bool)
    else:
        raise ValueError('Foreground mask contains values other than 0 and 255')

    # Calculate pixel-edge distance maps (PED) for each image
    dist_metric = cv2.DIST_L2       # Manhattan (L1), Euclidean (L2), Chess-King (C), etc.
    PED = np.zeros((n_cam, res[1], res[0]))
    print('Calculating pixel-edge distance maps for {} images...'.format(n_cam))
    for i in tqdm(range(n_cam)):
        edge_map = cv2.Canny(I[i], canny_low, canny_high)
        edge_map = (np.max(edge_map) - edge_map) / np.max(edge_map) # Reverse and normalise
        PED[i] = cv2.distanceTransform(np.uint8(edge_map), dist_metric, 0)
        PED[i, ~M[i]] = 0
        PED[i] = func.dist_map_transform(PED[i], edge_map) + ped_offset
    PED = np.int_(PED)

    # Foreground segmentation on adaptive maps
    print('Applying foreground mask on pixel-edge maps...')
    for i in tqdm(range(n_cam)):
        PED[i, ~M[i]] = 0

    # Merge depthmaps based on PED threshold (Use D1 near edges, D2 elsewhere)
    D = D1.copy()
    idx_merge = PED > thresh_merge
    D[idx_merge] = D2[idx_merge]
    print('\nMerging depthmaps based on pixel-edge distance threshold = {}'
          .format(thresh_merge))

    # ------------------- Depthmap adaptive smoothing -------------------------
    if (is_parallel):
        import multiprocessing as mp

        mp.freeze_support()                     # Required for Windows systems
        n_proc = mp.cpu_count() - 2             # Leave some cores free to avoid system overload
        if (n_proc < 2):                        # Ensure at least 2 processes for parallel execution
            n_proc = 2
        pool = mp.Pool(processes = n_proc)

        # Adaptive median smoothing based on PED (use larger median size for pixels farther from edges)
        print('Applying adaptive median filter on depthmaps...', flush=True)
        pbar = tqdm(total=n_cam, unit=' images')

        R = [pool.apply_async(func.adaptive_median_gm,
                              args=(D[i], np.int_(PED[i] * adap_median_multiplier)),
                              callback = pbar_update) for i in range(n_cam)]
        R = [r.get() for r in R]

        D_merged = np.zeros_like(D)
        median_sizes = np.zeros_like(D)
        for i,iv in enumerate(R):
            D_merged[i] = iv[0]
            median_sizes = iv[1]
        pbar.close()
        pool.close()
        pool.join()
    else:
        raise ValueError('Adaptive median smoothing is currently only implemented for parallel execution!')
    # -------------------------------------------------------------------------

    # Foreground masking on merged depthmaps
    print('Applying foreground mask on depthmaps...')
    for i in tqdm(range(n_cam)):
        D_merged[i, ~M[i]] = 0

    n_removed = np.sum(~M)
    print('Removed {:,} ({:.2f}%) points outside foreground mask'
            .format(n_removed, n_removed/n_pts*100))

    # Remove low confidence depth values based on fitness maps F1 and F2
    idx_1 = ~idx_merge & (F1 > thresh_F1)
    idx_2 = idx_merge & (F2 > thresh_F2)
    D_merged[idx_1] = 0
    D_merged[idx_2] = 0
    print('\nRemoved {:,} ({:.2f}%) points with fitness-error > {}'
          .format(np.sum(idx_1), np.sum(idx_1)/n_pts*100, thresh_F1))
    print('Removed {:,} ({:.2f}%) points with fitness-error > {}'
          .format(np.sum(idx_2), np.sum(idx_2)/n_pts*100, thresh_F2))

    # Remove out-of-bounds depth values based on bounds B_low and B_high
    D_merged[D_merged < B_low] = 0
    D_merged[D_merged > B_high] = 0
    n_low = np.sum((D_merged < B_low) & (D_merged != 0))  # Masked area is already 0
    n_high = np.sum(D_merged > B_high)
    print('Removed {:,} points with depth < {}'.format(n_low, B_low))
    print('Removed {:,} points with depth > {}'.format(n_high, B_high))

    # Print info on remaining points
    n_remaining = np.sum(D_merged != 0)
    print('Remaining points = {:,} / {:,} ({:.2f}%)'
          .format(n_remaining, n_pts, n_remaining/n_pts*100))

    # Print info on merge ratio
    # Note: There could be a mismatch between n_total and n_remaining.
    idx = (D_merged != 0)
    idx_1b = ~idx_merge & (F1 < thresh_F1)
    idx_2b = idx_merge & (F2 < thresh_F2)
    n_merge_1 = np.sum(idx & idx_1b)
    n_merge_2 = np.sum(idx & idx_2b)
    n_total = n_merge_1 + n_merge_2
    print('\nMerge stats: {:,} ({:.2f}%) + {:,} ({:.2f}%) = {:,}'.
          format(n_merge_1, n_merge_1 / n_total * 100,
                 n_merge_2, n_merge_2 / n_total * 100, n_total))

    # ------------------ Cross-view consistency check -------------------------
    # Load camera matrices
    fpath = path.join(data_path, dataset, dataset + '_P.mat')
    mfile = spio.loadmat(fpath)
    P = mfile['P']
    P = np.asarray(P, order='C')
    POS, ORN, ANG = func.cam_layout(P)

    # Cross-view consistency check parameters
    ang_low = 5         # Minimum angle between views [degrees]
    ang_high = 60       # Maximum angle between views [degrees]
    k = 3               # Minimum number of neighbors needed for consistency check
    d_tol = 0.001       # Absolute depth tolerance for consistency check

    D_cvc = np.zeros_like(D)
    C_cvc = np.zeros_like(D)
    print('\nApplying cross-view consistency check...', flush=True)

    # Apply cross-view consistency check for each depth map
    if (is_parallel):
        pbar = tqdm(total=n_cam, unit=' images')
        pool = mp.Pool(processes = n_proc)
        R = [pool.apply_async(func.crossview_consistency,
                              args=(i, D_merged, P, ANG, ang_low, ang_high, k, d_tol),
                              callback = pbar_update) for i in range(n_cam)]
        R = [r.get() for r in R]

        for i,iv in enumerate(R):
            D_cvc[i] = iv[0]
            C_cvc[i] = iv[1]
        pbar.close()
        pool.close()
        pool.join()
    else:
        for i in tqdm(range(n_cam)):
            D_cvc[i], C_cvc[i] = func.crossview_consistency(i, D_merged, P, ANG,
                                                            ang_low, ang_high, k, d_tol)
    # -------------------------------------------------------------------------

    # Print info on merge ratio (again)
    # Note: There could be a mismatch between n_total and n_remaining.
    idx = (D_cvc != 0)
    idx_1b = ~idx_merge & (F1 < thresh_F1)
    idx_2b = idx_merge & (F2 < thresh_F2)
    n_merge_1 = np.sum(idx & idx_1b)
    n_merge_2 = np.sum(idx & idx_2b)
    n_total = n_merge_1 + n_merge_2
    print('\nMerge stats: {:,} ({:.2f}%) + {:,} ({:.2f}%) = {:,}'.
          format(n_merge_1, n_merge_1 / n_total * 100,
                 n_merge_2, n_merge_2 / n_total * 100, n_total))

    # Write final depthmaps to scene directory
    if (is_write_scene):
        print('\nWriting {} depthmaps to scene {} with depth-level {}...'
              .format(n_cam, scene_idx, depth_level))
        for i in range(n_cam):
            Di = D_cvc[i].astype(np.float32) # Convert to float32 for MVE format
            fpath = scene_path + '\\views'\
                                + '\\view_' + "{:04d}".format(i) + '.mve'\
                                + '\\depth-L' + str(depth_level) + '.mvei'

            with open(fpath, 'wb') as f:
                # MVE_IMAGE signature: 89 4D 56 45 5F 49 4D 41 47 45 0A (hex)
                header = np.array((137, 77, 86, 69,
                                    95, 73, 77, 65, 71, 69, 10), dtype=np.uint8)
                header.tofile(f)
                # width, height
                header = np.asarray(res, dtype=np.uint32)
                header.tofile(f)
                # channels, image-type
                header = np.array((1, 9), dtype=np.uint32)
                header.tofile(f)
                # depth data
                Di.tofile(f)
        print('DONE!')
